### ISSUE TITLE
component.download_component(component,dir) errors if you use full component id

### ISSUE THREAD

**Issue by Cmheidelberg** [KnowledgeCaptureAndDiscovery/wings-client#12]
**Describe the bug**
using 
```
wings_instance = wings.init()
file_path = wings_instance.component.download_component("http://localhost:8080/export/users/mint/api-test/components/library.owl#HAND-1", "components")
``` 
will lead to a Invalid argument error:
```
Traceback (most recent call last):
File "test.py", line 74, in <module>
file_path = wings_instance.component.download_component("http://localhost:8080/export/users/mint/api-test/components/library.owl#HAND-1", "components")
File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\wings\component.py", line 120, in download_component 
with open(file_path, 'wb') as f: 
OSError: [Errno 22] Invalid argument: 'components\\http://localhost:8080/export/users/mint/api-test/components/library.owl#HAND-1.zip'
```
Im not sure if this important or not as the method works when you just put the last part of the component id, in this case HAND-1
```
wings_instance = wings.init()
file_path = wings_instance.component.download_component("HAND-1", "components")
``` 

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by mosoriob** [comment]
Please try:
```
file_path = wings_instance.component.download_component("HAND-1", "components")
```
